### ISSUE TITLE
build failure with multiple definition

### ISSUE THREAD

**Issue by davephillips** [raincheque/qwelk#1]
Linux Fedora 23
dev Rack

At link stage:

g++ -o plugin.so build/src/bitcounter.cpp.o build/src/qwelk.cpp.o build/src/automaton.cpp.o  -shared
build/src/automaton.cpp.o: In function `rack::MomentarySwitch::randomize()':
/home/dlphilp/src/Rack-test/plugins/qwelk/src/automaton.cpp:44: multiple definition of `ModuleAutomaton::step()'
build/src/bitcounter.cpp.o:/home/dlphilp/src/Rack-test/plugins/qwelk/src/bitcounter.cpp:44: first defined here
build/src/automaton.cpp.o: In function `WidgetAutomaton::WidgetAutomaton()':
/home/dlphilp/src/Rack-test/plugins/qwelk/src/automaton.cpp:82: multiple definition of `WidgetAutomaton::WidgetAutomaton()'
build/src/bitcounter.cpp.o:/home/dlphilp/src/Rack-test/plugins/qwelk/src/bitcounter.cpp:82: first defined here
build/src/automaton.cpp.o: In function `WidgetAutomaton::WidgetAutomaton()':
/home/dlphilp/src/Rack-test/plugins/qwelk/src/automaton.cpp:82: multiple definition of `WidgetAutomaton::WidgetAutomaton()'
build/src/bitcounter.cpp.o:/home/dlphilp/src/Rack-test/plugins/qwelk/src/bitcounter.cpp:82: first defined here
collect2: error: ld returned 1 exit status
../../compile.mk:43: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1

**Comment by raincheque** [comment]
@davephillips is this still happening with the latest version?

**Comment by davephillips** [comment]
No, your recent sources have been building fine here. Thanks for the cool modules, they're on my "must learn to use" list. :)

**Comment by raincheque** [comment]
great! thank you for giving them a try! if you have any questions ask away and don't hold back suggestions & ideas! have fun!
