### ISSUE TITLE
Indra's Net crashes 

### ISSUE THREAD

**Issue by the1andonlydrno** [raincheque/qwelk#10]
Hi, Indra's Net crashes VCV-Rack 0.6.2c on Windows, even when it is the only module.

**Comment by joopvdl** [comment]
I can confirm that.

**Comment by netboy3** [comment]
Just posted a pull request for V1. The upgrade also includes a bug fix for Indra's crash. I'll be posting freshly built binaries later today on the [migrate issue](https://github.com/raincheque/qwelk/issues/11) and would appreciate if you can test the plugins out.
