### ISSUE TITLE
Migrate to Rack v1

### ISSUE THREAD

**Issue by omni72** [raincheque/qwelk#11]
Hi - any plans or progress on migrating Qwelk to v1? It be great to have the Qwelk goodies in Rack v1 :)

Thanks & take care

**Comment by netboy3** [comment]
Just posted a pull request for V1. I'll be posting freshly built binaries later today and would appreciate if you can test the plugins out.

**Comment by netboy3** [comment]
Here are the plugins for your testing:
Linux: [Qwelk-1.0.0-lin.zip](https://github.com/raincheque/qwelk/files/3801977/Qwelk-1.0.0-lin.zip)
Mac: [Qwelk-1.0.0-mac.zip](https://github.com/raincheque/qwelk/files/3801978/Qwelk-1.0.0-mac.zip)
Windows: [Qwelk-1.0.0-win.zip](https://github.com/raincheque/qwelk/files/3801979/Qwelk-1.0.0-win.zip)

I have tested the Linux plugins and they seem to work fine.

**Comment by Petervos2018** [comment]
Hi @netboy3 , 
just tried The Qwelk suite on Windows 7 clicked the Indra Module in the VCV Browser and Rack crashed.

Here is the log.txt

[9.667 fatal src/main.cpp:39] Fatal signal 22. Stack trace:
31: ZN4rack10appDestroyEv 0x456435
30: raise 0xfd0a16f0
29: abort 0xfd0a537c
28: ZN11ModuleIndra7processERKN4rack6engine6Module11ProcessArgsE 0x7005556c
27: ZN11ModuleIndra7processERKN4rack6engine6Module11ProcessArgsE 0x7005556c
26: ZN11ModuleIndraC1Ev 0x7005f0d0
25: ZZN4rack11createModelI11ModuleIndra11WidgetIndraEEPNS_6plugin5ModelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel18createModuleWidgetEv 0x70073260
24: ZN4rack3app11AudioWidget12setAudioPortEPNS_5audio4PortE 0x497e2c
23: ZN4rack3app8ModelBox8onButtonERKNS_5event6ButtonE 0x757990
22: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x76d4b0
21: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x76d4b0
20: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x76d4b0
19: ZN4rack2ui12ScrollWidget8onButtonERKNS_5event6ButtonE 0x4a3964
18: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x76ca90
17: ZN4rack3app14BrowserOverlay8onButtonERKNS_5event6ButtonE 0x74df60
16: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x76ca90
15: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
14: ZN4rack7updater17isUpdateAvailableEv 0x45914e
13: glfwPlatformUnlockMutex 0x4d732e
12: TranslateMessageEx 0x76bb97e0
11: CallWindowProcW 0x76bb3a04
10: CallWindowProcW 0x76bb3a04
9: glDebugEntry 0xf325a170
8: TranslateMessageEx 0x76bb97e0
7: TranslateMessage 0x76bb95a8
6: glfwPlatformPollEvents 0x4da9a9
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x77c500
3: main 0x77c500
2: main 0x77c500
1: BaseThreadInitThunk 0x76cb5560
0: RtlUserThreadStart 0x76e13840

Hope you can do something with it.
Thanks for all your porting, don't know why you do it, but love that you do it, Thanks !

Peter.

**Comment by netboy3** [comment]
> just tried The Qwelk suite on Windows 7 clicked the Indra Module in the VCV Browser and Rack crashed.

Hi @Petervos2018,

Thank you for testing and letting me know about the issue. This never happened on Linux which is my main dev platform. I believe I found the bug and updated the binaries in the post above. Will you be so kind to download again and test? I appreciate your kind words. There's so much contribution in this project I felt bad not to do something myself and noticed that many folks miss a bunch of abandoned plugins, so decided to assist the community.

**Comment by Petervos2018** [comment]
@netboy3 , You Da Man (sorry ;)
Yes it works now, at least no crash, I don't know what they do yet, I have to spend some time with that.
Thank you again (I gather there was some useful info in the log.txt ?)

Greetings Peter.

**Comment by netboy3** [comment]
Great! You might want to read the README (though it doesn't include Indra's information). Some of them are very unconventional sequencers that implement CA (Cellular Automation). There's a good Wikipedia article about it, and some real nice [YouTube videos](https://www.youtube.com/watch?v=W1zKu3fDQR8). My choice in porting plugins are either ones that the community really misses, or ones that are really interesting and unusual. This one lands the second. The log info helped - thank you!
