### ISSUE TITLE
Plugin Manager

### ISSUE THREAD

**Issue by ghost** [raincheque/qwelk#4]
Hi! 

First of all I need to say I find your modules pretty useful. Keep up the good work!

I downloaded/installed your latest binaries for windows through the plugin manager today.  
After restarting Rack I saw that the red dot appears with your latest plugin.. so I looked into your makefile here on github and saw that you dont have a "VERSION=0.5.5" (the version of your latest modules) included in your makefile... which is needed that by the manager to know if this is the current version.. 
in the json file its 0.5.5 for your modules, therefor it needs also a VERSION= 0.5.5 in your makefile.. 

please add this and recompile, so we wont have the red dot with your module package anymore.
have a look into the tutorial makefile if you are not sure how to ;)

all the best, 
Michael

**Comment by raincheque** [comment]
Hello and thanks for trying out the modules. Sorry for the inconvenience caused. I will take care of it soon.
