### ISSUE TITLE
changes for 0.6 API

### ISSUE THREAD

**Issue by phdsg** [raincheque/qwelk#6]
hey there.  
are you interested in help from the Plugin Repair Team (https://github.com/VCVRack/community/issues/269) with upgrading to the new v0.6 API (https://github.com/VCVRack/Rack/issues/258#issuecomment-346222777)?

**Comment by DomiKamu** [comment]
Hi, no I'm not interested because I've upgraded "Ohmer" myself to the new v0.6 API, now they're compatible with v0.6. Thanks to have replied.

**Comment by phdsg** [comment]
https://github.com/raincheque/qwelk/pull/8
@raincheque just a friendly bump.
hoping that you'll get the notification...
0.6 is almost here now.

**Comment by phdsg** [comment]
`0.6` ready binaries:
https://github.com/phdsg/qwelk/issues/1

**Comment by raincheque** [comment]
Hey! I haven't had time to check out 0.6 and apparently it has changed a lot. there's a 0.6  pull request pending, I think. Will accept that once I check it out.

**Comment by phdsg** [comment]
thx, i hope you haven't completely abandoned vcvrack...
i'd still like to see indra :)

**Comment by raincheque** [comment]
I stopped using vcv when 0.5 came out and it became real slow on my machine + I can't borrow a Mac to build with anymore. I think there's a build team now? I really have to start reading the threads I guess.

**Comment by phdsg** [comment]
yes there's a build team now (currently only andrew) that's taking care of building the plugins that are accepted into the community repo.
the [library team](https://github.com/VCVRack/community/issues/352) will take care of updating the community repo.
